
export type VehicleStatus = 'Available' | 'Sold' | 'Pending';

export interface Vehicle {
  id: string;
  make: string;
  model: string;
  year: number;
  price: number;
  mileage: number;
  status: VehicleStatus;
  imageUrl: string;
  vin: string;
  location?: string;
  transmission?: string;
  fuelType?: string;
  bodyType?: string;
  color?: string;
  engineSize?: string;
  doors?: number;
  seats?: number;
  features?: string[];
  description?: string;
  condition?: string;
  serviceHistory?: string;
  contactPhone?: string;
  contactEmail?: string;
}

export interface Dealership {
  id: string;
  name: string;
  location: string;
  vehicles: Vehicle[];
}

export type CustomerStatus = 'Active' | 'Lead' | 'VIP' | 'Prospect';
export type CustomerType = 'Individual' | 'Business' | 'Government';

export interface Customer {
  id: string;
  initials: string;
  name: string;
  company: string;
  email: string;
  phone: string;
  location: string;
  type: CustomerType;
  status: CustomerStatus;
  totalSpent: number;
  purchases: number;
  enquiries: number;
  lastContact: string;
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  timestamp: Date;
  read: boolean;
  type: 'vehicle' | 'customer';
}

export interface DashboardAlert {
  level: 'Low' | 'Medium' | 'High' | 'Info';
  type: string;
  description: string;
  date: string;
  count?: number;
}

export interface DashboardRecentAction {
  type: string;
  user?: string;
  role: string;
  timestamp: string;
}

export interface DepartmentPerformance {
  name: string;
  target: number;
  achieved: number;
  budget: number;
  change: number;
}

export interface DashboardData {
  totalRevenue: number;
  systemUsers: number;
  systemHealth: number;
  alerts: DashboardAlert[];
  quickActions: {
    pendingApprovals: number;
  };
  recentActions: DashboardRecentAction[];
  departmentPerformance: DepartmentPerformance[];
}

export interface CustomerDashboardData {
  totalCustomers: number;
  activeCustomers: number;
  vipCustomers: number;
  activeLeads: number;
  totalRevenue: number;
}

export interface SalesAnalyticsValue {
  value: number;
  change: number;
}

export interface SalesAnalyticsData {
  kpis: {
    totalRevenue: SalesAnalyticsValue;
    vehiclesSold: SalesAnalyticsValue;
    conversionRate: SalesAnalyticsValue;
    avgDealSize: SalesAnalyticsValue;
  };
  salesTrend: Array<{
    month: string;
    vehicles: number;
    revenue: number;
  }>;
  vehicleCategories: Array<{
    name: string;
    vehicles: number;
    percentage: number;
    color: string;
  }>;
  teamPerformance: Array<{
    initials: string;
    name: string;
    role: string;
    sales: number;
    revenue: number;
    target: number;
    trend: 'up' | 'down';
  }>;
  salesFunnel: Array<{
    stage: string;
    value: number;
    percentage: number;
  }>;
}

export interface DocumentVaultData {
  kpis: {
    total: number;
    totalSize: string;
    active: number;
    archived: number;
    storageUsed: number;
    storageLimit: number;
  };
  insights: {
    expiring: { title: string; description: string };
    compliance: { title: string; description: string };
    security: { title: string; description: string };
  };
  documents: Array<{
    name: string;
    size: string;
    tags: string[];
    type: string;
    description: string;
  }>;
}

export type ReportQuickActionIcon =
  | 'trendingUp'
  | 'car'
  | 'users'
  | 'chartBar';

export interface ReportsData {
  kpis: {
    generated: number;
    downloads: number;
    scheduled: number;
    storageUsed: number;
    storageLimit: number;
  };
  insights: {
    autoGenerated: { title: string; description: string };
    smartScheduling: { title: string; description: string };
    storageOptimization: { title: string; description: string };
  };
  availableReports: Record<
    string,
    Array<{
      name: string;
      description: string;
      lastRun: string;
      format: string;
      size: string;
      frequency: string;
    }>
  >;
  recentReports: Array<{
    name: string;
    category: string;
    status: string;
    date: string;
    format: string;
    downloads: number;
    categoryColor: string;
  }>;
  quickActions: Array<{
    name: string;
    icon: ReportQuickActionIcon;
    active: boolean;
  }>;
}
