import type { ReportsData } from '../types';

export const REPORTS_DATA: ReportsData = {
  kpis: {
    generated: 247,
    downloads: 1432,
    scheduled: 12,
    storageUsed: 2.8,
    storageLimit: 10,
  },
  insights: {
    autoGenerated: {
      title: 'Auto-Generated Insights',
      description: '5 trend reports ready for monthly review. Key patterns identified.',
    },
    smartScheduling: {
      title: 'Smart Scheduling',
      description: 'Optimal report timing based on data freshness. 12 reports can be automated.',
    },
    storageOptimization: {
      title: 'Storage Optimization',
      description: '28% storage can be freed by archiving old reports. Archive 89 reports older than 6 months.',
    },
  },
  availableReports: {
    "Sales Reports": [
      { name: 'Monthly Sales Summary', description: 'Comprehensive monthly sales breakdown', lastRun: 'Jan 15, 2024', format: 'PDF', size: '2.4 MB', frequency: 'Monthly' },
      { name: 'Sales Performance by Team', description: 'Individual and team performance metrics', lastRun: 'Jan 14, 2024', format: 'Excel', size: '1.8 MB', frequency: 'Weekly' },
      { name: 'Revenue Trend Analysis', description: 'Revenue patterns and forecasting', lastRun: 'Jan 10, 2024', format: 'PDF', size: '3.2 MB', frequency: 'Quarterly' },
      { name: 'Deal Pipeline Report', description: 'Active deals and conversion rates', lastRun: 'Jan 15, 2024', format: 'PDF', size: '1.5 MB', frequency: 'Daily' },
    ],
    "Inventory Reports": [
      { name: 'Vehicle Inventory Status', description: 'Current stock levels and availability', lastRun: 'Jan 15, 2024', format: 'Excel', size: '2.1 MB', frequency: 'Daily' },
      { name: 'Aging Inventory Analysis', description: 'Vehicles by time on lot', lastRun: 'Jan 13, 2024', format: 'PDF', size: '1.9 MB', frequency: 'Weekly' },
      { name: 'New Arrivals Summary', description: 'Recently added vehicles', lastRun: 'Jan 12, 2024', format: 'PDF', size: '1.2 MB', frequency: 'Weekly' },
      { name: 'Vehicle Performance Report', description: 'Sales performance by make/model', lastRun: 'Jan 10, 2024', format: 'Excel', size: '2.8 MB', frequency: 'Monthly' },
    ],
    "Customer Reports": [
      { name: 'Customer Acquisition Report', description: 'New customers and lead sources', lastRun: 'Jan 12, 2024', format: 'PDF', size: '1.6 MB', frequency: 'Monthly' },
      { name: 'Customer Satisfaction Survey', description: 'Customer feedback and ratings', lastRun: 'Jan 13, 2024', format: 'Excel', size: '2.2 MB', frequency: 'Quarterly' },
      { name: 'Lead Conversion Analysis', description: 'Enquiry to sale conversion rates', lastRun: 'Jan 14, 2024', format: 'Excel', size: '1.5 MB', frequency: 'Weekly' },
      { name: 'Customer Retention Report', description: 'Repeat customers and loyalty metrics', lastRun: 'Jan 5, 2024', format: 'PDF', size: '2.0 MB', frequency: 'Quarterly' },
    ],
    "Financial Reports": [
      { name: 'Profit & Loss Statement', description: 'Revenue, costs, and profitability', lastRun: 'Jan 14, 2024', format: 'Excel', size: '3.5 MB', frequency: 'Monthly' },
      { name: 'Commission Report', description: 'Sales commissions by staff', lastRun: 'Jan 13, 2024', format: 'PDF', size: '1.7 MB', frequency: 'Monthly' },
      { name: 'Tax Summary Report', description: 'VAT and tax calculations', lastRun: 'Jan 10, 2024', format: 'Excel', size: '2.2 MB', frequency: 'Quarterly' },
      { name: 'Cash Flow Analysis', description: 'Inflows and outflows tracking', lastRun: 'Jan 15, 2024', format: 'PDF', size: '1.8 MB', frequency: 'Weekly' },
    ],
  },
  recentReports: [
    { name: 'Daily Sales Summary', category: 'Sales', status: 'Ready', date: 'Jan 15, 2024', format: 'PDF', downloads: 23, categoryColor: 'bg-green-100 text-green-800' },
    { name: 'Inventory Status Update', category: 'Inventory', status: 'Ready', date: 'Jan 15, 2024', format: 'Excel', downloads: 15, categoryColor: 'bg-blue-100 text-blue-800' },
    { name: 'Monthly P&L Statement', category: 'Financial', status: 'Ready', date: 'Jan 14, 2024', format: 'Excel', downloads: 8, categoryColor: 'bg-purple-100 text-purple-800' },
    { name: 'Customer Acquisition Report', category: 'Customer', status: 'Ready', date: 'Jan 12, 2024', format: 'PDF', downloads: 12, categoryColor: 'bg-orange-100 text-orange-800' },
    { name: 'Team Performance Report', category: 'Sales', status: 'Processing', date: 'Jan 14, 2024', format: 'Excel', downloads: 0, categoryColor: 'bg-green-100 text-green-800' },
  ],
  quickActions: [
    { name: 'Sales Summary', icon: 'trendingUp', active: true },
    { name: 'Inventory Report', icon: 'car', active: false },
    { name: 'Customer Analysis', icon: 'users', active: false },
    { name: 'Financial Report', icon: 'chartBar', active: false },
  ],
};
